all: exe1.11 exe1.10 exe1.9
exe1.11:exe1.11.cpp
	g++ -Wall -o exe1.11 exe1.11.cpp
exe1.10:exe1.10.cpp
	g++ -Wall  -o exe1.10 exe1.10.cpp
exe1.9:exe1.9.cpp
	g++ -Wall -o exe1.9 exe1.9.cpp
clean:	
	rm exe1.11 exe1.10 exe1.9
